# Name for the experiment
project_name: ""


##### REFERENCE FILES #####
# Name of the genome or transcriptome fasta file to align on
fasta: ""

# Name of the gff file with genome or transcriptome annotations
gff: ""

# Fasta file with not interesting sequences
fasta_outRNA: ""


##### TRIMMING #####
# Are the sequencing adapters already removed in fastq files ? 'yes' or 'no'
already_trimmed: ""

# Adapter sequence (Example sequence for Illumina TruSeq™ single or CD index : "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA")
adapt_sequence: ""


##### LENGTHS SELECTION #####
# Minimum read length kept for ribosome profiling
readsLength_min: "25"

# Maximum read length kept for ribosome profiling
readsLength_max: "35"


##### GFF #####
# Feature of the annotation file to select during counting (usually "CDS")
gff_cds_feature: "CDS"

# Feature defining a transcript (usually "mRNA" or "transcript")
gff_mRNA_feature: "mRNA"

# Feature defining a transcript (usually "five_prime_UTR" or "5UTR")
gff_5UTR_feature: "five_prime_UTR"

# Attribut linking CDS to its related transcript feature in the annotation file (usually "Parent")
gff_parent_attribut: "Parent"

# Attribut containing the name of the feature in the annotation file (usually 'Name')
gff_name_attribut: "Name"


##### DIFFERENTIAL ANALYSIS #####
# Name of the reference condition (same as file name)
reference_condition: ""

# Thresholds to adjust for differential expression analysis
p-val: "0.01"
logFC: "0"


##### QUALITATIVE ANALYSIS #####
# Choose between "ribowaltz", "trip" or "none"
# riboWaltz requires a lot of ressources
# RiboDoc needs a specific gff format
qualitative_analysis: "ribowaltz"

# Number of bases to look before the start and after the stop for periodicity (relative positions)
window_utr: "15"

# Number of bases to look after the start and before the stop for periodicity (relative positions)
window_cds: "30"


########## Optional and only for qualitative_analysis: "trip" ##########
# Does UTR covering has to be calculated ('yes' or 'no'). You need the corresponding length files if set to 'yes'
UTR: "no"

# The length options will be ignore if UTR is set on 'yes'
# File with CDS lengths
CDSlength: ""

# File with 5-prime UTR lengths
5primelength: ""

# File with 3-prime UTR lengths
3primelength: ""

# Elements for UTRs have to be specified only if you put 'yes' for the 'UTR' option
gff_5UTR_feature: "three_prime_UTR"
###########################################################################
